# Welcome to Jekyll!
#

# Site settings
title: Introducción a la Ingeniería en Software
description: Hi, I´m Adrian Coello
owner: Adrian Coello # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: https://mail.google.com/mail/u/1/#inbox
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vico2001.github.io/#.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/Adrian91826823
  github: https://github.com/Vico2001
  facebook-official: https://www.facebook.com/pg/Adrian-Coello-Beginner-Developer-107318994102574/posts/?ref=page_internal
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
